#!/bin/bash
dns_config="domain-needed;no-resolv;local=/"$DOMAIN"/;domain="$DOMAIN";addn-hosts=/home/dnsmasq/hosts"
dhcp_config="expand-hosts;dhcp-authoritative;cache-size=150;dhcp-leasefile=/home/dnsmasq/dhcp.leases;dhcp-range="$DHCP_RANGE","$DHCP_RELAY_TIME""
dns_file="/home/dnsmasq/dns-server"

SET-CONFIG() {
  configlist=$1
  for config in $(echo $configlist | tr ";" "\n")
  do
    echo $config >> /etc/dnsmasq.conf
  done
}

ADD-DNS-SERVER() {
  if [ -f $dns_file ]; then
    for line in $(cat $file) ; do
      echo server=$line >> /etc/dnsmasq.conf
    done < $dns_file
  else
    echo "DNS server file not found!"
}

INIT () {
  echo "server registeriation start ..."
  rm /etc/dnsmasq.conf
  touch /etc/dnsmasq.conf
  SET-CONFIG $dns_config
  ADD-DNS-SERVER
  SET-CONFIG $dhcp_config
  cat /etc/dnsmasq.conf
  echo "server registeriation ... done"
  dnsmasq -k
}

INIT