#!/bin/bash
config_template="/etc/dnsmasq.conf.bk"
config_file="/etc/dnsmasq.conf"
dns_file="/home/dnsmasq/dns-server"

ADD-DNS-SERVER() {
  if [ -f $dns_file ]; then
    for line in $(cat $dns_file) ; do
      echo server=$line >> $config_file
    done
  else
    echo "DNS server file not found!"
  fi
}

INIT () {
  # create dnsmasq config file from config template
  sed "/local=/clocal=/"$DOMAIN"/" $config_template > $config_file
  sed -i "/domain=/cdomain="$DOMAIN"" $config_file
  sed -i "/dhcp-range=/cdhcp-range="$DHCP_RANGE","$DHCP_RELAY_TIME"" $config_file
  ADD-DNS-SERVER
  cat $config_file
  echo "dnsmasq starting ..."
  dnsmasq -k
}

INIT